import type { CalibrationAnchor } from './config.js';

/**
 * GENERATED by `pnpm --filter @18-0/data analyze -- --write`. Do not hand-edit.
 *
 * Fitted 2026-09-01 against 300,000 games simulated on the
 * real 1999-2025 dataset (2,994 cards).
 * Regenerating changes every future score, so bump the model version with it.
 */
export const GENERATED_CALIBRATION_ANCHORS: readonly CalibrationAnchor[] = [
  { raw: 50.3714, final: 30 },
  { raw: 75.3714, final: 58 },
  { raw: 78.2971, final: 64 },
  { raw: 80.7311, final: 68 },
  { raw: 82.9854, final: 71.5 },
  { raw: 86.8963, final: 76 },
  { raw: 90.6285, final: 80 },
  { raw: 92.7895, final: 87 },
  { raw: 94.1584, final: 92 },
  { raw: 94.865, final: 95 },
  { raw: 96.032, final: 97.5 },
  { raw: 97.209, final: 99 },
  { raw: 98.0668, final: 99.35 },
  { raw: 99.6661, final: 99.6 },
  { raw: 100, final: 100 },
];
