import type { CalibrationAnchor } from './config.js';

/**
 * GENERATED by `pnpm calibrate`. Do not hand-edit.
 *
 * Fitted 2026-09-01 against 1,000,000 simulated rosters
(4 leagues, seed 1).
 * Regenerating changes every future score, so bump the model version with it.
 */
export const GENERATED_CALIBRATION_ANCHORS: readonly CalibrationAnchor[] = [
  { raw: 55.1727, final: 30 },
  { raw: 80.1727, final: 58 },
  { raw: 82.8546, final: 64 },
  { raw: 84.98, final: 68 },
  { raw: 86.9123, final: 71.5 },
  { raw: 90.2579, final: 76 },
  { raw: 94.2499, final: 80 },
  { raw: 96.99, final: 87 },
  { raw: 98.051, final: 92 },
  { raw: 98.546, final: 95 },
  { raw: 99.34, final: 97.5 },
  { raw: 100.056, final: 99 },
  { raw: 100.581, final: 99.35 },
  { raw: 101.758, final: 99.6 },
];
