import type { CalibrationAnchor } from './config.js';

/**
 * GENERATED by `pnpm --filter @18-0/data analyze -- --write`. Do not hand-edit.
 *
 * Fitted 2026-09-01 against 300,000 games simulated on the
 * real 1999-2025 dataset (6,209 cards).
 * Regenerating changes every future score, so bump the model version with it.
 */
export const GENERATED_CALIBRATION_ANCHORS: readonly CalibrationAnchor[] = [
  { raw: 47.6438, final: 30 },
  { raw: 72.6438, final: 58 },
  { raw: 75.6355, final: 64 },
  { raw: 78.1593, final: 68 },
  { raw: 80.5593, final: 71.5 },
  { raw: 84.9471, final: 76 },
  { raw: 89.7299, final: 80 },
  { raw: 92.4101, final: 87 },
  { raw: 93.8919, final: 92 },
  { raw: 94.6406, final: 95 },
  { raw: 95.8853, final: 97.5 },
  { raw: 97.101, final: 99 },
  { raw: 97.9134, final: 99.35 },
  { raw: 99.6357, final: 99.6 },
  { raw: 100, final: 100 },
];
