/**
 * Emits the SQL that loads the bundled dataset into Postgres.
 *
 *   pnpm --filter @18-0/data seed:sql > supabase/seed/0001_dataset.sql
 *
 * The client plays offline from the JSON; the database needs the same rows so
 * the server can score authoritatively without trusting anything the client
 * sends (PRFAQ §36).
 */
import { DATASET, ERA_TABLE, displayName } from '../index.js';

const quote = (v: string) => `'${v.replace(/'/g, "''")}'`;
const array = (values: readonly string[]) =>
  `'{${values.map((v) => `"${v.replace(/"/g, '\\"')}"`).join(',')}}'`;

const out: string[] = [
  '-- GENERATED by `pnpm --filter @18-0/data seed:sql`. Do not hand-edit.',
  `-- Dataset ${DATASET.version} · model ${DATASET.ratingModelVersion} · ${DATASET.cards.length} cards`,
  'begin;',
  '',
  'truncate table public.season_cards, public.franchise_eras, public.franchises, public.eras cascade;',
  '',
];

out.push('insert into public.eras (key, label, start_year, end_year, sort_order) values');
out.push(
  ERA_TABLE.filter((e) => DATASET.eras.some((d) => d.key === e.key))
    .map((e, i) => `  (${quote(e.key)}, ${quote(e.label)}, ${e.startYear}, ${e.endYear}, ${i})`)
    .join(',\n') + ';',
);
out.push('');

out.push('insert into public.franchises (id, abbreviation, display_name, nickname, conference, primary_color, logo_url) values');
out.push(
  DATASET.franchises
    .map(
      (f) =>
        `  (${quote(f.id)}, ${quote(f.abbr)}, ${quote(f.name)}, ${quote(f.nick)}, ${quote(f.conference)}, ${quote(f.color)}, ${quote(f.logo)})`,
    )
    .join(',\n') + ';',
);
out.push('');

out.push('insert into public.franchise_eras (franchise_id, era_key, spin_weight) values');
out.push(
  DATASET.combos
    .map((c) => `  (${quote(c.franchiseId)}, ${quote(c.era)}, ${c.spinWeight})`)
    .join(',\n') + ';',
);
out.push('');

// Cards go in batches so a single statement never gets unreasonably large.
const BATCH = 500;
for (let i = 0; i < DATASET.cards.length; i += BATCH) {
  const batch = DATASET.cards.slice(i, i + BATCH);
  out.push(
    'insert into public.season_cards (id, entity_id, entity_type, display_name, position, franchise_id, season_year, era_key, rating, archetypes, rating_model_version) values',
  );
  out.push(
    batch
      .map(
        (c) =>
          `  (${quote(c.id)}, ${quote(c.entityId)}, ${quote(c.position === 'DEF' ? 'defense' : 'player')}, ` +
          `${quote(displayName(c))}, ${quote(c.position)}, ${quote(c.franchiseId)}, ${c.year}, ${quote(c.era)}, ` +
          `${c.rating}, ${array(c.archetypes)}, ${quote(DATASET.ratingModelVersion)})`,
      )
      .join(',\n') + ';',
  );
  out.push('');
}

out.push('commit;');
console.log(out.join('\n'));
