#!/bin/bash
#
# Build 18-0 and install it on a connected Android device or a running
# emulator.
#
#   pnpm android:device                  # first attached device
#   pnpm android:device emulator-5554    # a specific one
#
# Release, not Debug, for the same reason as iOS: Release embeds the JavaScript
# bundle, so the app runs with no Metro and no laptop. A Debug build installs
# fine and then needs a bundler on the same network, which is the tethered
# workflow wearing a different hat.
#
# **The release build is signed with the debug keystore.** That is the Expo
# template's default and it is deliberate here: it makes a local install work
# with no key management at all. It also means this APK can never go to Play —
# a store build needs a real upload key, which belongs in EAS credentials
# rather than in this repository.
set -euo pipefail

cd "$(dirname "$0")/.."

export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
export PATH="$ANDROID_HOME/platform-tools:$PATH"
if [[ ! -d "$ANDROID_HOME" ]]; then
  echo "Android SDK not found at $ANDROID_HOME" >&2
  exit 1
fi

# EXPO_PUBLIC_* values are inlined into the bundle at build time, so the app
# carries the backend with it rather than depending on this machine.
if [[ -f .env ]]; then
  set -a; . ./.env; set +a
fi

SERIAL="${1:-}"
if [[ -z "$SERIAL" ]]; then
  SERIAL=$(adb devices | awk 'NR>1 && $2=="device" { print $1; exit }')
fi
if [[ -z "$SERIAL" ]]; then
  echo "No Android device or emulator found." >&2
  echo "Start one with:  emulator -avd \$(emulator -list-avds | head -1)" >&2
  exit 1
fi
echo "→ device $SERIAL"

[[ -d android ]] || npx expo prebuild -p android

# `expo run:android` would also try to start Metro, which a Release build does
# not need and which fails when the port is busy with another project.
#
# The JVM arguments are set here rather than in android/gradle.properties
# because that file is regenerated by every prebuild and the setting would be
# lost. The template's default metaspace is not enough to compile this many
# native modules — the build dies with a bare "What went wrong: Metaspace"
# after two minutes, which names the cause and nothing else.
#
# Only the target's own architecture is built. The default is a universal APK
# carrying native libraries for all four ABIs, which came out at 111 MB and
# made the emulator's package service fall over mid-install ("Broken pipe",
# then "Can't find service: package"). A store build wants every ABI; a local
# install wants the one the device can actually run.
ABI=$(adb -s "$SERIAL" shell getprop ro.product.cpu.abi 2>/dev/null | tr -d '\r')
echo "→ architecture ${ABI:-all}"

( cd android && ./gradlew assembleRelease \
    -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m" \
    ${ABI:+-PreactNativeArchitectures="$ABI"} )

APK=$(find android/app/build/outputs/apk/release -name '*.apk' 2>/dev/null | head -1)
[[ -n "$APK" ]] || { echo "Built, but no APK was produced." >&2; exit 1; }
echo "→ $APK ($(du -h "$APK" | cut -f1))"

adb -s "$SERIAL" install -r "$APK"
adb -s "$SERIAL" shell monkey -p com.eighteenzero.app -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1 || true

echo
echo "Installed and launched."
