#!/usr/bin/env python3
"""
Map every player in the dataset to their headshot on the NFL's CDN.

    mkdir -p /tmp/rosters
    for y in $(seq 1999 2025); do
      curl -sL -o /tmp/rosters/$y.csv \
        https://github.com/nflverse/nflverse-data/releases/download/rosters/roster_$y.csv
    done
    curl -sL -o /tmp/players.csv \
      https://github.com/nflverse/nflverse-data/releases/download/players/players.csv
    python3 scripts/build-headshots.py /tmp/rosters /tmp/players.csv

Writes packages/data/src/headshots.ts.

Only the URL is stored, never the image. Bundling 1,548 photographs would add
tens of megabytes to a download for a game whose whole pitch is that it works
offline with no account, and the pictures are not ours to redistribute.

players.csv alone covers about a quarter of these players, because it carries
headshots for active players and most of this dataset retired years ago. The
per-season rosters carry the rest, so both are read and the rosters win.

The URLs share one of two prefixes, so only the trailing token is stored: 57 KB
instead of 151 KB, for a file that ships inside the app bundle.
"""
from __future__ import annotations

import csv
import glob
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATASET = ROOT / 'packages' / 'data' / 'generated' / 'dataset.json'
OUT = ROOT / 'packages' / 'data' / 'src' / 'headshots.ts'

PREFIXES = [
    'https://static.www.nfl.com/image/private/f_auto,q_auto/league/',
    'https://static.www.nfl.com/image/upload/f_auto,q_auto/league/',
]


def main(roster_dir: str, players_csv: str) -> None:
    found: dict[str, str] = {}

    # Season rosters first: they cover retired players, which is most of this
    # dataset. The earliest file to name somebody wins, which is arbitrary but
    # stable, and a headshot does not meaningfully change between seasons.
    for path in sorted(glob.glob(f'{roster_dir}/*.csv')):
        for row in csv.DictReader(open(path)):
            gsis, url = row.get('gsis_id'), row.get('headshot_url')
            if gsis and url:
                found.setdefault(gsis, url)

    for row in csv.DictReader(open(players_csv)):
        gsis, url = row.get('gsis_id'), row.get('headshot_url')
        if gsis and url:
            found.setdefault(gsis, url)

    cards = json.load(open(DATASET))['cards']
    # Team defences have no person to photograph.
    wanted = sorted({c['entityId'] for c in cards if c['position'] != 'DEF'})

    tokens: dict[str, str] = {}
    other: dict[str, str] = {}
    for entity in wanted:
        url = found.get(entity)
        if not url:
            continue
        for index, prefix in enumerate(PREFIXES):
            if url.startswith(prefix):
                tokens[entity] = f'{index}{url[len(prefix):]}'
                break
        else:
            other[entity] = url

    body = '\n'.join(f"  '{k}': '{v}'," for k, v in sorted(tokens.items()))
    extra = '\n'.join(f"  '{k}': '{v}'," for k, v in sorted(other.items()))
    covered = len(tokens) + len(other)

    OUT.write_text(f'''/**
 * Where to find a player's photograph.
 *
 * GENERATED by scripts/build-headshots.py from nflverse's season rosters. Do
 * not edit by hand: rerun the script.
 *
 * URLs only. The images stay on the NFL's CDN and are fetched when a card is
 * opened, because bundling {covered} photographs would add tens of megabytes to
 * a game whose pitch is that it works offline, and they are not ours to
 * redistribute.
 *
 * The first character of each value selects a prefix from PREFIXES, which is
 * why these are tokens rather than URLs: it takes the file from 151 KB to 57 KB
 * for something that ships inside the app.
 *
 * {covered} of the dataset's players. Team defences have nobody to photograph
 * and are absent by design.
 */
const PREFIXES = [
  {json.dumps(PREFIXES[0])},
  {json.dumps(PREFIXES[1])},
];

const TOKEN: Readonly<Record<string, string>> = {{
{body}
}};

const FULL: Readonly<Record<string, string>> = {{
{extra}
}};

/** The player's headshot, or null when there is not one. */
export function headshotUrl(entityId: string): string | null {{
  const full = FULL[entityId];
  if (full) return full;
  const token = TOKEN[entityId];
  if (!token) return null;
  const prefix = PREFIXES[Number(token[0])];
  return prefix ? prefix + token.slice(1) : null;
}}
''')
    print(f'{OUT.relative_to(ROOT)}  {covered} of {len(wanted)} players  '
          f'{OUT.stat().st_size // 1024} KB')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else '/tmp/rosters',
         sys.argv[2] if len(sys.argv) > 2 else '/tmp/players.csv')
