/**
 * Where this game lives, and how it describes itself to a link scraper.
 *
 * This module deliberately imports nothing. It is read at runtime by the share
 * code and at build time by `app/+html.tsx`, which renders the HTML shell in
 * Node — anything reaching for `react-native` from here would break the web
 * export.
 */

/**
 * The game's own domain, and the canonical address for every share and tag.
 *
 * The build is also mirrored on GitHub Pages at `mutaaf.github.io/18-0`, which
 * is where it lived first. That copy declares this URL as its canonical one, so
 * the two deployments are one page to a search engine and one link in a chat.
 * Anything written here is what a scraper reads; see `public/index.html`, which
 * carries the same strings for the served HTML.
 */
export const APP_URL = 'https://18-0.co';

/** How the link reads when it is shown as text rather than followed. */
export const APP_URL_LABEL = APP_URL.replace(/^https?:\/\//, '').replace(/\/+$/, '');

export const APP_NAME = '18-0';

export const APP_TAGLINE = 'Build the perfect roster';

/**
 * Under 200 characters, because that is roughly where iMessage, Slack and
 * Twitter each stop showing it.
 */
export const APP_DESCRIPTION =
  'Seven spins, sixty years of pro football, one shot at an undefeated season. ' +
  'Build a roster from the greatest seasons ever played and see how far it gets.';

/** 1200x630, generated by scripts/make-og.py. Absolute — scrapers do not resolve relative paths. */
export const OG_IMAGE = `${APP_URL}/og.png`;

/**
 * The privacy policy, at the game's own address.
 *
 * It is served as static HTML from `public/privacy.html` rather than linked out
 * to the publisher's site, for a reason worth recording: the publisher's page
 * renders its text in JavaScript. A store reviewer's crawler, and Google's
 * OAuth consent-screen checker, fetch the URL without running any — so what
 * they saw at the old address was a marketing shell with no policy in it.
 *
 * It describes the analytics the game actually sends, which is checked against
 * the code rather than written from a template -- including the claim that
 * deleting an account deletes the analytics with it, which the delete-account
 * function keeps. Changing what is sent means changing that page in the same
 * pass. See docs/analytics.md.
 *
 * Registered with Apple, Google Play and the Google OAuth consent screen. It
 * cannot move again without editing all three.
 */
export const PRIVACY_URL = `${APP_URL}/privacy`;

/**
 * The public TestFlight link for the iOS beta.
 *
 * Public rather than an invite: anyone with the URL can join, up to Apple's
 * 10,000 external testers, without an email being collected first.
 *
 * The link is live before the build behind it is. External testing needs Beta
 * App Review, and while that is pending TestFlight answers the link with "this
 * beta isn't accepting testers right now" -- which reads like a fault and is
 * only a queue. Worth knowing before assuming the URL is wrong.
 */
export const TESTFLIGHT_URL = 'https://testflight.apple.com/join/Q79YnwEs';

/** The repository, and the folder inside it that Chrome is pointed at. */
export const REPO_URL = 'https://github.com/mutaaf/18-0';
export const EXTENSION_URL = `${REPO_URL}/tree/main/extensions/espn-watch`;

/**
 * The whole repository as a zip, because that is what "Download the folder"
 * has to mean for somebody who does not have git.
 *
 * GitHub's own archive URL rather than a release asset: there is no release,
 * and a link to one that does not exist is a download button that 404s.
 */
export const EXTENSION_ZIP_URL = `${REPO_URL}/archive/refs/heads/main.zip`;

/**
 * What to hand an agent.
 *
 * It names the repository, the folder inside it and the page to open, because
 * an agent given "install the 18-0 extension" will guess at all three -- and
 * the guess that matters is the folder: the repository root is not an
 * extension and Chrome refuses it with an error about a missing manifest.
 *
 * It ends by saying what success looks like. An agent that has loaded an
 * extension has no way to know whether it worked, and "the card is in the first
 * row" is checkable by looking.
 */
export function agentPrompt(): string {
  return [
    `Clone ${REPO_URL} and load its browser extension in Chrome for me.`,
    '',
    'The extension is the folder extensions/espn-watch — not the repository root,',
    'which has no manifest and which Chrome will refuse.',
    '',
    'Open chrome://extensions, turn on Developer mode, choose Load unpacked and',
    'point it at that folder. Then open https://www.espn.com/watch/ and tell me',
    'whether the 18-0 card is in the first row.',
  ].join('\n');
}
