/**
 * Where this game lives, and how it describes itself to a link scraper.
 *
 * This module deliberately imports nothing. It is read at runtime by the share
 * code and at build time by `app/+html.tsx`, which renders the HTML shell in
 * Node — anything reaching for `react-native` from here would break the web
 * export.
 */

export const APP_URL = 'https://mutaaf.github.io/18-0';

/** How the link reads when it is shown as text rather than followed. */
export const APP_URL_LABEL = APP_URL.replace(/^https?:\/\//, '').replace(/\/+$/, '');

export const APP_NAME = '18-0';

export const APP_TAGLINE = 'Build the perfect roster';

/**
 * Under 200 characters, because that is roughly where iMessage, Slack and
 * Twitter each stop showing it.
 */
export const APP_DESCRIPTION =
  'Seven spins, sixty years of pro football, one shot at an undefeated season. ' +
  'Build a roster from the greatest seasons ever played and see how far it gets.';

/** 1200x630, generated by scripts/make-og.py. Absolute — scrapers do not resolve relative paths. */
export const OG_IMAGE = `${APP_URL}/og.png`;

/**
 * The privacy policy, on the publisher's own domain.
 *
 * It lives at digitalcraftai.com rather than beside the game because the game
 * is published by DigitalCraft AI and this is the address given to Apple and
 * Google at review. A policy on a project subpath of a github.io account reads
 * as a hobby page, and moving it later means a store metadata change.
 *
 * It currently states that the game carries no analytics, which is true while
 * EXPO_PUBLIC_POSTHOG_KEY is unset. Setting that key makes the policy wrong
 * until it is updated -- see docs/analytics.md for what has to change, and in
 * which two store forms.
 */
export const PRIVACY_URL = 'https://digitalcraftai.com/privacy';
